### ISSUE TITLE
Releases?

### ISSUE THREAD

**Issue by jasongabler** [rmoreas/ShibbolethBundle#20]
Hello,

Do you have any interest in creating release tags for this bundle? I load your bundle as a dependency of other bundles I've created. So,  composer in my main project, for which I am not a fan of using minimum-stability=dev, gets unhappy because your bundle as a 3rd tier dependency is not stable, for example:

    - ucsf-iam/shibauthbundle 0.1.5 requires kuleuven/shibboleth-bundle dev-master -> satisfiable by kuleuven/shibboleth-bundle[dev-master] but these conflict with your requirements or minimum-stability.

I can always fork and create my own tags, of course. But before I make an perfect mirror of your work, I thought'd I'd ask about tags first.

Thanks,

Jason Gabler

**Comment by rmoreas** [comment]
Hi Jason,

Sure I’m willing to do this. I’ll do it next Wednesday, meanwhile I’ll process the pending merge request too.

Regards,
Ronny

**Comment by rmoreas** [comment]
Hi Jason,
2 release tags are created: 1.0.0 before merge of 2 latest pull requests and 1.1.0 after the merge.

Best regards,
Ronny

**Comment by jasongabler** [comment]
Ronny,

This is great. Thanks for being so responsive!

Jason
